on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

name: Build

jobs:
  make:
    strategy:
      matrix:
        package: [gcalert, lightdm-webkit-theme-tendou, lightdm-webkit-theme-wisp]
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      env:
        PACKAGE: ${{ matrix.package }}
        AUR_DEPENDENCIES: lightdm-webkit2-greeter
      volumes:
        - ${{ github.workspace }}:/vol
      options: --workdir /vol
    steps:
      - uses: actions/checkout@v2
      - run: |
          pacman -Sy --noconfirm --noprogressbar base-devel git
          echo 'nobody ALL=NOPASSWD:ALL' >> /etc/sudoers
          chown -R nobody /vol/$PACKAGE && cd /vol/$PACKAGE
          sudo -u nobody makepkg -sri --noconfirm --noprogressbar
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: make
    strategy:
      matrix:
        package: [gcalert, lightdm-webkit-theme-tendou, lightdm-webkit-theme-wisp]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - env:
          PACKAGE: ${{ matrix.package }}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
          mkdir -p ~/.ssh
          echo "Host aur" > ~/.ssh/config
          echo "  HostName aur.archlinux.org" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/aur" >> ~/.ssh/config
          echo "  User aur" >> ~/.ssh/config
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/aur
          ssh-keyscan aur.archlinux.org > ~/.ssh/known_hosts
          chmod -R 600 ~/.ssh/{aur,config,known_hosts}
          git remote add $PACKAGE-remote aur:$PACKAGE.git
          git subtree push --prefix=$PACKAGE $PACKAGE-remote master
