on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

name: Build

jobs:
  make:
    strategy:
      matrix:
        package: [gcalert, lightdm-webkit-theme-tendou, lightdm-webkit-theme-wisp]
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      env:
        PACKAGE: ${{ matrix.package }}
        AUR_DEPENDENCIES: lightdm-webkit2-greeter
      volumes:
        - ${{ github.workspace }}:/vol
      options: --workdir /vol
    steps:
      - uses: actions/checkout@v2
      - run: |
          pacman -Sy --noconfirm --noprogressbar base-devel git
          echo 'nobody ALL=NOPASSWD:ALL' >> /etc/sudoers
          chown -R nobody /vol/$PACKAGE && cd /vol/$PACKAGE
          sudo -u nobody makepkg -sri --noconfirm --noprogressbar
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: make
    strategy:
      matrix:
        package: [gcalert, lightdm-webkit-theme-tendou, lightdm-webkit-theme-wisp]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          PACKAGE: ${{ matrix.package }}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
          sudo mkdir -p $HOME/.ssh
          echo "Host aur.archlinux.org" | sudo tee -a $HOME/.ssh/config
          echo "  IdentityFile $HOME/.ssh/aur" | sudo tee -a $HOME/.ssh/config
          echo "  User aur" | sudo tee -a $HOME/.ssh/config
          echo "$SSH_PRIVATE_KEY" | sudo tee -a $HOME/.ssh/aur > /dev/null
          sudo chmod -R 600 $HOME/.ssh
          ssh-keyscan -v aur.archlinux.org | sudo tee -a $HOME/.ssh/known_hosts
          git remote add $PACKAGE aur@aur.archlinux.org:$PACKAGE.git
          git subtree push --prefix=$PACKAGE $PACKAGE master
